# Generated by Django 5.2.16 on 2026-08-03 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_sales_phase6_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_returned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sale',
            name='internal_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='sale',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacist_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_source',
            field=models.CharField(choices=[('pos', 'POS'), ('manual', 'Manual'), ('online', 'Online')], default='pos', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card / POS'), ('mobile_money', 'Mobile Money (Telebirr/CBE)'), ('bank_transfer', 'Bank Transfer'), ('split', 'Split Payment'), ('other', 'Other')], default='cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('held', 'Held'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Fully Refunded')], default='completed', max_length=30),
        ),
    ]
