# Generated by Django 5.2.16 on 2026-07-27 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_inventory_phase5_models'),
        ('tenants', '0002_auth_phase3_user_login_history_password_reset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0, help_text='Current available balance')),
                ('initial_quantity', models.IntegerField(default=0, help_text='Initial quantity when received')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase/cost price', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Retail selling price', max_digits=10)),
                ('expiry_date', models.DateField(help_text='Expiration date')),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ('expiry_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out (FIFO)'), ('adjustment', 'Stock Adjustment'), ('expired_discard', 'Expired Discard'), ('return', 'Customer Return')], max_length=30)),
                ('quantity_changed', models.IntegerField(help_text='Positive for addition, negative for deduction')),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenants.tenant')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='inventory.stockbatch')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'batch_number'), name='unique_batch_per_product_tenant'),
        ),
    ]
