# Generated by Django 5.2.16 on 2026-08-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_inventory_phase5_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='batch_status',
            field=models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved'), ('damaged', 'Damaged'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='purchase_order_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='reorder_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='reserved_quantity',
            field=models.IntegerField(default=0, help_text='Quantity reserved for pending orders'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='stock_status',
            field=models.CharField(default='in_stock', max_length=30),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='warehouse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='transaction_type',
            field=models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out (FIFO)'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Inventory Transfer'), ('archive', 'Batch Archive'), ('restore', 'Batch Restore'), ('expired_discard', 'Expired Discard'), ('return', 'Customer Return')], max_length=30),
        ),
    ]
