# Generated by Django 5.2.16 on 2026-08-13 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('tenants', '0004_featureflag_userinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='tenants.tenant'),
        ),
    ]
