# Generated by Django 5.2.16 on 2026-07-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10, help_text='Minimum stock threshold for low-stock alerts'),
        ),
    ]
